[package]
name = "volatix"
description = "An in memory database"
readme = "README.md"
version = "0.1.0"
edition = "2024"
authors = ["Juan Milkah <juanmilkah@gmail.com>"]
license = "MIT"

[workspace]
resolve = "2"
members = ["server", "cli", "volatix-bench"]

[workspace.dependencies]
anyhow = "1.0.98"
parking_lot = "0.12.3"
rand = "0.9.1"

[[bin]]
name = "server"
path = "server/src/main.rs"

[[bin]]
name ="cli"
path = "cli/src/main.rs"

[lib]
name = "server_lib"
path = "server/src/lib.rs"

[[bin]]
name = "volatix-bench"
path = "volatix-bench/src/main.rs"

[dependencies]
anyhow.workspace = true
rand.workspace = true
parking_lot.workspace = true
