[package]
name = "volatix"
description = "An in memory database"
readme = "README.md"
version = "0.1.0"
edition = "2024"
authors = ["Juan Milkah <juanmilkah@gmail.com>"]
license = "MIT"
rust-version = "1.88"

[workspace]
members = ["server", "cli", "volatix-bench"]

[[bin]]
name = "server"
path = "server/src/main.rs"

[[bin]]
name ="cli"
path = "cli/src/main.rs"

[lib]
name = "server_lib"
path = "server/src/lib.rs"

[[bin]]
name = "volatix-bench"
path = "volatix-bench/src/main.rs"

[workspace.dependencies]
anyhow = "1.0.98"
bincode2 = "2.0.1"
ctrlc = "3.4.7"
flate2 = "1.1.1"
parking_lot = "0.12.3"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }

[dependencies]
anyhow = {workspace = true}
bincode2 = {workspace = true}
ctrlc = {workspace = true}
flate2 = {workspace = true}
parking_lot = {workspace = true}
rand = {workspace = true}
serde = {workspace = true}

[profile.release]
# debug = true
strip = true
lto = "fat"
opt-level = "s"
codegen-units = 1
