[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true}
anyhow = {workspace = true}
flate2 = {workspace =true}
bincode2 = {workspace =true}

[[bin]]
name = "server"
path = "src/main.rs"

[lib]
name = "server_lib"
path = "src/lib.rs"

